### ISSUE TITLE
What is the purpose of align_model

### ISSUE THREAD

**Issue by datonefaridze** [BrixIA/Brixia-score-COVID-19#10]
Hello, I made everything work, segmentation works (it is almost perfect), but i don't understand what is the purpose of align_model, how can i use it?

**Comment by datonefaridze** [comment]
@msavardi @BrixIA  can you answer this?

**Comment by msavardi** [comment]
To avoid the inclusion of anatomical parts not belonging to the lungs in the AI pipeline, which would increase the task complexity and introduce unwanted biases, we integrate into the network an alignment block. 

Alignment is achieved through a spatial transformer network able to estimate the spatial transform matrix in order to center, rotate, and correctly zoom the lungs. The spatial transformer network estimates a six-valued affine transform that is used to resample (by bilinear interpolation) and align all features at various scales produced by the multi-resolution backbone, before they are forwarded to the ROI (Region Of Interest) Pooling.

Hope this clears your doubt 😃

**Comment by datonefaridze** [comment]
is it necessary to use it? i tested and segmentation model works well, do i have to use align_model too? what i mean is: segmentation model is working well but it still needs improvement, can i use align_model to improve it's masking ability?

**Comment by msavardi** [comment]
The alignment is already applied in the flow toward the extraction of the BrixiaScore

**Comment by adityaa1510** [comment]
> Hello, I made everything work, segmentation works (it is almost perfect), but i don't understand what is the purpose of align_model, how can i use it?

can you please provide me the implementation of this repo

**Comment by msavardi** [comment]
The implementation can be found on folder `src`
